apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patient-service.fullname" . }}
  labels:
    app: {{ include "patient-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "patient-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "patient-service.name" . }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
        - name: {{ include "patient-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ default .Values.global.image.tag .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
